### ISSUE TITLE
unable to resolve class javax.annotation.PreDestroy

### ISSUE THREAD

**Issue by PoojaGidaveer** [rabbitmq/rabbitmq-jms-boot-demo#1]
When we run spring run consumer.groovy producer.groovy command we are getting the following error
-groovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (jar:file:/C:/Users/XXX/Downloads/spring-boot-cli-1.5.8.RELEASE-bin/spring-1.5.8.RELEASE/lib/spring-boot-cli-1.5.8.RELEASE.jar!/BOOT-INF/lib/groovy-2.4.12.jar!/) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
startup failed:

```
file:/C:/Users/XXX/Desktop/SUPA/CF/rabbitmq-jms-client-spring-boot-trader-demo-master/consumer.groovy: -1: unable to resolve class javax.annotation.PreDestroy
 @ line -1, column -1.
file:/C:/Users/XXX/Desktop/SUPA/CF/rabbitmq-jms-client-spring-boot-trader-demo-master/consumer.groovy: -1: unable to resolve class javax.annotation.PostConstruct
 @ line -1, column -1.
file:/C:/Users/XXX/Desktop/SUPA/CF/rabbitmq-jms-client-spring-boot-trader-demo-master/producer.groovy: -1: unable to resolve class javax.annotation.PreDestroy
 @ line -1, column -1.
file:/C:/Users/XXX/Desktop/SUPA/CF/rabbitmq-jms-client-spring-boot-trader-demo-master/producer.groovy: -1: unable to resolve class javax.annotation.PostConstruct
 @ line -1, column -1.
4 errors
```

**Comment by gregturn** [comment]
What version of Java are you using?

**Comment by Sandyroy95** [comment]
Hi, We're using java 1.8

**Comment by gregturn** [comment]
This code fragment was written for a blog article four years ago so I don't know it's present status.

**Comment by michaelklishin** [comment]
I cannot reproduce on JDK 8 u144. I bumped spring-boot-starter-parent to match the most recent 1.x release.

Our team does not use GitHub issues for investigations, please start a rabbitmq-users thread if this is still relevant.
